# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{starter}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Iktkin"]
  s.date = %q{2010-09-12}
  s.email = %q{nicolas.papon@webflows.fr}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".idea/dictionaries/nico.xml",
     ".idea/encodings.xml",
     ".idea/misc.xml",
     ".idea/modules.xml",
     ".idea/starter.iml",
     ".idea/vcs.xml",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/generators/itkin/config/USAGE",
     "lib/generators/itkin/config/config_generator.rb",
     "lib/generators/itkin/haml/USAGE",
     "lib/generators/itkin/haml/haml_generator.rb",
     "lib/generators/itkin/haml/templates/_%singular_name%.html.haml.tt",
     "lib/generators/itkin/haml/templates/_actions.html.haml.tt",
     "lib/generators/itkin/haml/templates/_form.html.haml.tt",
     "lib/generators/itkin/haml/templates/_index.html.haml.tt",
     "lib/generators/itkin/haml/templates/_item.html.haml.tt",
     "lib/generators/itkin/haml/templates/edit.html.haml.tt",
     "lib/generators/itkin/haml/templates/index.html.haml.tt",
     "lib/generators/itkin/haml/templates/show.html.haml.tt",
     "lib/generators/itkin/scaffold/USAGE",
     "lib/generators/itkin/scaffold/scaffold_generator.rb",
     "lib/generators/itkin/scaffold_controller/USAGE",
     "lib/generators/itkin/scaffold_controller/scaffold_controller_generator.rb",
     "lib/generators/itkin/scaffold_controller/templates/controller.rb",
     "lib/starter.rb",
     "test/helper.rb",
     "test/test_starter.rb"
  ]
  s.homepage = %q{http://github.com/itkin/starter}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Usefull custom generators}
  s.test_files = [
    "test/helper.rb",
     "test/test_starter.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

