# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{starter}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Itkin"]
  s.date = %q{2010-09-22}
  s.email = %q{nicolas.papon@webflows.fr}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/generators/itkin/config/USAGE",
     "lib/generators/itkin/config/config_generator.rb",
     "lib/generators/itkin/javascript/javascript_generator.rb",
     "lib/generators/itkin/javascript/templates/admin.js",
     "lib/generators/itkin/javascript/templates/lib/itkin/ajax_accordion.js",
     "lib/generators/itkin/javascript/templates/lib/itkin/ajax_multipart_form.js",
     "lib/generators/itkin/javascript/templates/lib/itkin/custom_effects.js",
     "lib/generators/itkin/javascript/templates/lib/itkin/search_box.js",
     "lib/generators/itkin/javascript/templates/lib/itkin/sortable_accordion.js",
     "lib/generators/itkin/javascript/templates/lib/jquery.livequery.js",
     "lib/generators/itkin/javascript/templates/lib/jquery.livequery.min.js",
     "lib/generators/itkin/sass/sass_generator.rb",
     "lib/generators/itkin/sass/templates/admin_exemple.sass",
     "lib/generators/itkin/sass/templates/itkin/_ajax-accordion.sass",
     "lib/generators/itkin/sass/templates/itkin/_form.sass",
     "lib/generators/itkin/scaffold/USAGE",
     "lib/generators/itkin/scaffold/scaffold_generator.rb",
     "lib/generators/itkin/scaffold/templates/controller.rb",
     "lib/generators/itkin/scaffold/templates/helper.rb",
     "lib/generators/itkin/scaffold/templates/migration.rb",
     "lib/generators/itkin/scaffold/templates/model.rb",
     "lib/generators/itkin/scaffold/templates/test/fixtures.yml",
     "lib/generators/itkin/scaffold/templates/test/functional.rb",
     "lib/generators/itkin/scaffold/templates/test/unit.rb",
     "lib/generators/itkin/scaffold/templates/views/_%singular_name%.html.haml.tt",
     "lib/generators/itkin/scaffold/templates/views/_actions.html.haml.tt",
     "lib/generators/itkin/scaffold/templates/views/_form.html.haml.tt",
     "lib/generators/itkin/scaffold/templates/views/_index.html.haml.tt",
     "lib/generators/itkin/scaffold/templates/views/_item.html.haml.tt",
     "lib/generators/itkin/scaffold/templates/views/edit.html.haml.tt",
     "lib/generators/itkin/scaffold/templates/views/index.html.haml.tt",
     "lib/generators/itkin/scaffold/templates/views/new.html.haml.tt",
     "lib/generators/itkin/scaffold/templates/views/show.html.haml.tt",
     "lib/generators/itkin/scaffold/templates/views/update.html.haml.tt",
     "lib/starter.rb",
     "starter.gemspec",
     "test/helper.rb",
     "test/test_starter.rb"
  ]
  s.homepage = %q{http://github.com/itkin/starter}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Usefull custom generators}
  s.test_files = [
    "test/helper.rb",
     "test/test_starter.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

